# Name: Shant Hairapetian
# Project: Lab6

# This is a Makefile for my lab assignment. It allows me to easily and accurately rebuild
# the lab assignment.


all: mole spiritd

mole: mole.c
	gcc -o mole mole.c

spiritd: spiritd.c
	gcc -o spiritd spiritd.c

